name: Publish to GitHub Package

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      package-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean Maven
        run: mvn clean

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin

      - name: Set Package Version
        run: mvn org.codehaus.mojo:versions-maven-plugin:2.14.2:set -DnewVersion=${{ inputs.package-version }}

      - name: Build and Publish
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
